name: rtfm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - langchain
  - openai
  - python-dotenv
  - tiktoken
  - numpy
  - pandas
  - pydantic
  - scikit-learn
  - nltk
  - spacy
  - pydantic-settings
  - jupyter
  - pip
  - streamlit
  - pip:
      - langchain-openai
      - psycopg2-binary
      - pgvecto_rs[sdk]
